### ISSUE TITLE
Support Diesel 2.0/Master

### ISSUE THREAD

**Issue by oeed** [quodlibetor/diesel-derive-newtype#13]
I know this crate is little old now, but it'd be great to have this working again with Diesel 2.0 (master branch) - although I'd understand reservations as it's not technically stable. A number of changes in Diesel appear to have broken this crate sadly.

**Comment by quodlibetor** [comment]
It's old, but it's as maintained as it needs to be, there aren't a ton of features it needs.

I'd be very happy for this to support 2.0/master, I didn't realize it was broken. I'd definitely take a PR, otherwise I'll look into it some time, maybe this weekend although I've got some other priorities that might bump it back.

If anyone's interested I'd be happy to look at wip PRs.

**Comment by dessalines** [comment]
Its probably okay for now, as diesel 2.0 isn't stable yet. And once it is, the custom type changes shouldn't be too different.

**Comment by dessalines** [comment]
Question, have the diesel devs shown any interest at bringing this into diesel itself? I just added this and its incredibly useful to strictly to some columns, especially those with a lot of foreign key constraints. 

cc @weiznich

**Comment by weiznich** [comment]
As I'm currently barley able to maintain what's already in diesel itself I'm not interested in adding more stuff to diesel itself, at least as long as it cannot be provided by a third party crate.

**Comment by bitemyapp** [comment]
Thank you very much for writing this crate! I've found it extremely helpful as we have _many_ foreign key relationships in our schema.

e.g. 
![image](https://user-images.githubusercontent.com/320177/155187396-23ef1fd1-a716-4a5a-8fe7-179c3966ed95.png)

If I can figure out how, I'll update this library for 2.0 when Diesel has a stable or at least RC 2.0 release out the door.

I'll report back if I get stuck, otherwise, you'll get a PR if you don't get to it before I do. I'm happy either way.

**Comment by quodlibetor** [comment]
There is a 2.0.0-rc.0 release on crates.io, and there is a diesel-2 branch in this repo that folks can feel free to PR against.

When 2.0 final comes out I'll try to release a version of this with nothing but a version bump, but PRs will be welcome.

**Comment by bitemyapp** [comment]
@quodlibetor it seems based on what you're saying here that the library works as-is against Diesel 2.0, is that right?

**Comment by quodlibetor** [comment]
In my testing, if you use the `diesel-derive-newtype = "2.0.0-rc.0"` in your Cargo.toml then it does. Any problems with that can be PR'd against the `diesel-2` branch in this repo.

**Comment by quodlibetor** [comment]
I've updated the readme to make that clearer.
